project:
  type: website
  output-dir: docs

website:
  title: "Pedagogisk portfölj"
  navbar:
    left:
      - text: "Om mig"
        href: index.qmd
      - text: "Pedagogiska ställningstaganden"
        href: stallningstaganden.qmd
      - text: "Kvalitativ redogörelse"
        href: kvalitativ.qmd
      - text: "Pedagogiskt CV"
        href: dokumentation.qmd
      - text: "Bilagor"
        href: bilagor.qmd
  page-footer:
    right: "[ORCID 0000-0002-0958-0094](https://orcid.org/0000-0002-0958-0094)"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    lang: sv
    toc: true
    toc-title: "På denna sida"
    toc-depth: 3
    smooth-scroll: true
